### ISSUE TITLE
open empty log file

### ISSUE THREAD

**Issue by LiangZhang1996** [wingsweihua/colight#17]
There always exist EOFError.
pipline.py 228
logging_data = pickle.load(f_logging_data)
EOFError: Ran out of input

**Comment by wingsweihua** [comment]
This should be caused by previous errors.

**Comment by hch211** [comment]
> There always exist EOFError.
> pipline.py 228
> logging_data = pickle.load(f_logging_data)
> EOFError: Ran out of input

Hello, have you solved this issue?

**Comment by LiangZhang1996** [comment]
> > There always exist EOFError.
> > pipline.py 228
> > logging_data = pickle.load(f_logging_data)
> > EOFError: Ran out of input
> 
> Hello, have you solved this issue?

It must be that you did not save the log file which contains the states, you should check the working folder, if it contains files like that "inter_{}.pkl"

**Comment by LJW0306** [comment]
@LiangZhang1996 你好 我想和您交流一下

**Comment by LJW0306** [comment]
我也出现了这个问题
