### ISSUE TITLE
error in updater.py, total_samples_inter_{}.pkl can't find

### ISSUE THREAD

**Issue by LiangZhang1996** [wingsweihua/colight#20]
At the `load_sample_with_forget(self,i)` part, open the `total_samples_inter_{}.pkl `, but never  touch this file.

Over the code, can't find any part that builds this file.

This may influence the update process.

**Comment by LiangZhang1996** [comment]
sorry, solved.

**Comment by LuckyLeeLL** [comment]
> sorry, solved.

Excuse me,  how do you solve this problem， i have the same question.

**Comment by LuckyVoasem** [comment]
me too，i have the same question.
