### ISSUE TITLE
Results on Colight and dqn

### ISSUE THREAD

**Issue by twodog0508** [wingsweihua/colight#50]
I conducted experiments using dqn and colight methods on a 6x6 network, and the final results were as follows:
Dqn: Final Travel Time is 214.5438, mean rewards: -14.1031, queue: 0.4005, delay: 0.0308, throughput: 4652 Total time token: 18397.876304388046
Colight: Final Travel Time is 206.8853, mean rewards: -4.6692, queue: 0.1022, delay: 0.0111, throughput: 4650 Total time token: 16563.93673968315

It seems that there is not much difference in the results between the two methods. Is it my mistake in implementing the method?

**Comment by LJW0306** [comment]
@twodog0508 Hello, I have been reading this article recently. Could you please communicate with me? This is my WeChat: Ljw_36
