### ISSUE TITLE
Questino about how to get the performance

### ISSUE THREAD

**Issue by BackMountainDevil** [wingsweihua/colight#51]
Paper: "Table 2: Performance on synthetic data and real-world data w.r.t average travel time. CoLight is the best"

In the code, to get the att(average travel time), run the summary_multi_anon.py and get data from file and then calculate the att.

But I find we can get it from CityFlow.eng: self.eng.get_average_travel_time(). Why not use that as att result? Is there a diff?

**Comment by LJW0306** [comment]
@BackMountainDevil Hello, I have been reading this article recently. Could you please communicate with me? This is my WeChat: Ljw_36

**Comment by BackMountainDevil** [comment]
#12
