### ISSUE TITLE
A quick question about the datasets 

### ISSUE THREAD

**Issue by IvanLLL** [wingsweihua/colight#7]
Hi, 

I notice that there are three volumns of Hangzhou datasets as well as Jinan datasets in the `data` folder.

**Hangzhou:**
- anon_4_4_hangzhou_real.json
- anon_4_4_hangzhou_real_5734.json
- anon_4_4_hangzhou_real_5816.json

**Jinan**
- anon_3_4_jinan_real_2000.json
- anon_3_4_jinan_real_2500.json
- anon_3_4_jinan_real.json

It is not very clear which ones were being measured in the performance table (i.e., Table 2) of your paper.

![table](https://user-images.githubusercontent.com/26270002/70672946-cc48b300-1cbb-11ea-880e-f73d8a373a90.png)

Thanks a lot.

**Comment by wingsweihua** [comment]
We provide those datasets for the researchers' need for more datasets. Our paper uses the ones without the number suffix.
